apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  namespace: default
  name: mybackend
spec:
  # https://cloud.google.com/load-balancing/docs/user-defined-request-headers
  # https://blog.doit-intl.com/farewell-maxmind-geolocating-requests-with-google-load-balancer-for-free-7938f5adbef0
  # https://github.com/kubernetes/ingress-gce/pull/795/files
  customRequestHeaders:
    headers:
    - "X-REGION:{client_region}"
